# -*- coding: utf-8 -*-
"""Dash_launch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0LIAYKtXspyIPUq3XA_kPkI2w4kC-LE
"""

import pandas as pd
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_dash.csv"
data = pd.read_csv(url)

data.head()

!wget "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/spacex_dash_app.py"

!pip install pandas dash
!pip install flask-ngrok
from dash import Dash, html, dcc, Input, Output
from flask import Flask
from flask_ngrok import run_with_ngrok
import plotly.express as px
import pandas as pd

# Загрузка данных
spacex_df = data

# Создаем сервер Flask
server = Flask(__name__)
app = Dash(__name__, server=server)
run_with_ngrok(server)  # Запускаем ngrok

# Получаем уникальные значения сайтов запусков
launch_sites = spacex_df['Launch Site'].unique()
options = [{'label': site, 'value': site} for site in launch_sites]
options.insert(0, {'label': 'All Sites', 'value': 'ALL'})  # Добавляем опцию "All Sites"

# Определяем минимальные и максимальные значения для слайдера
min_payload = spacex_df['Payload Mass (kg)'].min()
max_payload = spacex_df['Payload Mass (kg)'].max()

# Определяем макет приложения
app.layout = html.Div([
    html.H1("SpaceX Launch Dashboard"),

    dcc.Dropdown(
        id='site-dropdown',
        options=options,
        value='ALL',  # Значение по умолчанию
        multi=False  # Не разрешаем множественный выбор
    ),

    dcc.Graph(id='success-pie-chart'),  # График для отображения результатов

    # Добавляем слайдер для выбора диапазона нагрузки
    dcc.RangeSlider(
        id='payload-slider',
        min=0,  # Минимальное значение (0 кг)
        max=10000,  # Максимальное значение (10000 кг)
        step=1000,  # Интервал (1000 кг)
        value=[min_payload, max_payload],  # Текущий выбранный диапазон
        marks={i: str(i) for i in range(0, 10001, 1000)}  # Метки на слайдере
    ),

    # Новый график для отображения зависимости между нагрузкой и результатом запуска
    dcc.Graph(id='success-payload-scatter-chart')
])

# Callback функция для обновления графика на основе выбранного сайта и диапазона нагрузки
@app.callback(
    Output('success-pie-chart', 'figure'),
    Input('site-dropdown', 'value'),
    Input('payload-slider', 'value')
)
def update_pie_chart(selected_site, payload_range):
    if selected_site == 'ALL':
        # Если выбраны все сайты, считаем общее количество успешных запусков
        filtered_df = spacex_df[
            (spacex_df['Payload Mass (kg)'] >= payload_range[0]) &
            (spacex_df['Payload Mass (kg)'] <= payload_range[1])
        ]
        success_counts = filtered_df['class'].value_counts()
        labels = ['Failed', 'Success']
        values = [success_counts.get(0, 0), success_counts.get(1, 0)]
    else:
        # Фильтруем данные для выбранного сайта
        filtered_df = spacex_df[
            (spacex_df['Launch Site'] == selected_site) &
            (spacex_df['Payload Mass (kg)'] >= payload_range[0]) &
            (spacex_df['Payload Mass (kg)'] <= payload_range[1])
        ]
        success_counts = filtered_df['class'].value_counts()
        labels = ['Failed', 'Success']
        values = [success_counts.get(0, 0), success_counts.get(1, 0)]

    # Создаем график
    fig = px.pie(names=labels, values=values, title=f'Success Counts for {selected_site}')
    return fig

# Callback функция для обновления графика рассеяния на основе выбранного сайта и диапазона нагрузки
@app.callback(
    Output('success-payload-scatter-chart', 'figure'),
    Input('site-dropdown', 'value'),
    Input('payload-slider', 'value')
)
def update_scatter_chart(selected_site, payload_range):
    if selected_site == 'ALL':
        # Если выбраны все сайты, отображаем все данные
        filtered_df = spacex_df[
            (spacex_df['Payload Mass (kg)'] >= payload_range[0]) &
            (spacex_df['Payload Mass (kg)'] <= payload_range[1])
        ]
    else:
        # Фильтруем данные для выбранного сайта
        filtered_df = spacex_df[
            (spacex_df['Launch Site'] == selected_site) &
            (spacex_df['Payload Mass (kg)'] >= payload_range[0]) &
            (spacex_df['Payload Mass (kg)'] <= payload_range[1])
        ]

    # Создаем график рассеяния
    fig = px.scatter(
        filtered_df,
        x='Payload Mass (kg)',
        y='class',
        color='Booster Version Category',
        title=f'Payload vs. Mission Outcome for {selected_site}',
        labels={'class': 'Mission Outcome (1 = Success, 0 = Failure)'}
    )

    return fig

if __name__ == '__main__':
    app.run()

